---
unicorn:
  engine:
    actor: 
      system: UnicornActorSystem
    enable:
      remote: 
        actor: false
    remote: 
      bind: 
        port: 8995
  redis:
    database: 0
    expireTime: 120960000
    maxIdleConnections: 5
    maxTotalConnections: 10
    minIdleConnections: 1
    port: 8080
    timeout: 10000
  swagger:
    contact: ~
    description: "Unicorn REST API Explorer with Swagger Documentation"
    license: ~
    licenseUrl: ~
    termsOfServiceUrl: ~
    title: "Unicorn REST API Explorer with Swagger"
    version: "0.0.1"
server:
  context-path: /unicorn-api
management:
  context-path: /actuator
security:
  basic:
    enabled: true
  user:
    name: admin
    password: unicorn_admin
time:
  redisExpire:
    value: 33.6
    unit: hours
  redisTimeout:
    value: 10
    unit: seconds